spring:
  datasource:
    url: jdbc:mysql://localhost:3306/frame
    username: root
    password: root
  mybatis:
    mapper-location: classpath*:mapper/*.xml
    config-location: classpath:mybatis-config.xml
  thymeleaf:
    cache: false

---
logging:
  file: /logs/zhaopin.log

---
server:
  port: 8080
  tomcat:
    access_log_enabled: true
    basedir: target/tomcat
---
flyway:
  check-location: true
  locations: classpath:db/migration
  enabled: true
  encoding: utf-8
  sql-migration-prefix: V
  sql-migration-suffix: .sql


